server:
  port: 8082

spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crc982169622/config-repo.git
          username: crc982169622
          password: chen982169622
          search-paths: /eureka-provider
          basedir: E:\idea\config-repo